FROM ubuntu:22.04

# Install build dependencies (matching CI)
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    clang-19 \
    libvulkan-dev \
    libxcb1-dev \
    libx11-xcb-dev \
    libxcb-dri3-dev \
    libxcb-present-dev \
    libxcb-randr0-dev \
    libxcb-shm0-dev \
    libxcb-xfixes0-dev \
    libxcb-xkb-dev \
    libxkbcommon-x11-dev \
    libgl1-mesa-dev \
    libgtk-3-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy source files (submodules must be populated on the host first)
COPY . .

# Initialize simde submodule (nested, not in parent .gitmodules)
RUN cd /app/thirdparty/rexglue-sdk/thirdparty && \
    rm -rf simde && \
    git clone --depth 1 https://github.com/simd-everywhere/simde.git simde

# Generate FFmpeg headers (required by FFmpeg build)
RUN cat > /app/thirdparty/rexglue-sdk/thirdparty/FFmpeg/libavutil/avconfig.h << 'EOF'
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define HAVE_THREADS 1
#define HAVE_PTHREADS 1
#define HAVE_PRAGMA_DEPRECATED 1
#define HAVE_FAST_CLZ 1
#define HAVE_FAST_UNALIGNED 1
#define AV_HAVE_BIGENDIAN 0
#endif
EOF

cat > /app/thirdparty/rexglue-sdk/thirdparty/FFmpeg/libavutil/ffversion.h << 'EOF'
/* Automatically generated by CI, do not manually edit! */
#ifndef LIBAVUTIL_FFVERSION_H
#define LIBAVUTIL_FFVERSION_H
#define FFMPEG_VERSION "6.0"
#endif /* LIBAVUTIL_FFVERSION_H */
EOF

# Configure
RUN cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=clang-19 \
    -DCMAKE_CXX_COMPILER=clang++-19 \
    -DREXSDK_DIR=/app/thirdparty/rexglue-sdk \
    -DREXGLUE_USE_VULKAN=ON \
    -DREXGLUE_USE_D3D12=OFF

# Build SDK (always)
RUN cmake --build build --config Release --parallel $(nproc)

# Build main executable only if XEX asset is present
RUN if [ -f /app/assets/default.xex ]; then \
        cmake --build build --config Release --target ac6recomp_codegen --parallel $(nproc) && \
        cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang-19 \
            -DCMAKE_CXX_COMPILER=clang++-19 \
            -DREXSDK_DIR=/app/thirdparty/rexglue-sdk \
            -DREXGLUE_USE_VULKAN=ON \
            -DREXGLUE_USE_D3D12=OFF && \
        cmake --build build --config Release --parallel $(nproc); \
    fi

# Package (optional)
# RUN cd build && cpack -C Release
